"""Add tenant website settings

Revision ID: 40ca5acb145e
Revises: d1c20247f9cc
Create Date: 2026-05-28 16:51:11.943170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ca5acb145e'
down_revision = 'd1c20247f9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultant_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('specialisms', sa.Text(), nullable=True),
    sa.Column('sectors', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_available', sa.Boolean(), nullable=True),
    sa.Column('insurance_verified', sa.Boolean(), nullable=True),
    sa.Column('qualifications_verified', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tenant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_slug', sa.String(length=120), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('strapline', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('primary_colour', sa.String(length=20), nullable=True),
    sa.Column('accent_colour', sa.String(length=20), nullable=True),
    sa.Column('text_colour', sa.String(length=20), nullable=True),
    sa.Column('website_intro', sa.Text(), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('services_text', sa.Text(), nullable=True),
    sa.Column('sectors_text', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('cta_label', sa.String(length=100), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_slug'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_settings')
    op.drop_table('consultant_profile')
    # ### end Alembic commands ###
